# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "nvidia-layer"
BBFILE_PATTERN_nvidia-layer := "^${LAYERDIR}/"
LAYERSERIES_COMPAT_nvidia-layer := "whinlatter walnascar"

# Mirror NVIDIA GitLab repositories to GitHub
MIRRORS += "\
git://git@gitlab-master\.nvidia\.com.*/dgx/bmc/([\w-]+)\.git git://github.com/NVIDIA/\1.git;protocol=https \
git://git@gitlab-master\.nvidia\.com.*/dgx/([\w-]+)\.git git://github.com/NVIDIA/\1.git;protocol=https \
"

# Skip CVE check for all native and nativesdk recipes in this layer’s builds
CVE_CHECK_SKIP_RECIPE:class-native = "${PN}"
CVE_CHECK_SKIP_RECIPE:class-nativesdk = "${PN}"
