# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ax-nvidia-bmc-common-layer"
BBFILE_PATTERN_ax-nvidia-bmc-common-layer := "^${LAYERDIR}/"
LAYERSERIES_COMPAT_ax-nvidia-bmc-common-layer = "scarthgap styhead"
