# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            "

BBFILE_COLLECTIONS += "ax-nvidia-gb300nvl-bmc-layer"
BBFILE_PATTERN_ax-nvidia-gb300nvl-bmc-layer = "^${LAYERDIR}/"
LAYERSERIES_COMPAT_ax-nvidia-gb300nvl-bmc-layer = "scarthgap styhead"
