# The list contains manually added issues, which are not applicable for GB200NVL-BMC machine

CVE_STATUS[CVE-2021-3714] = "not-applicable-config: required config CONFIG_KSM is not in linux-aspeed"

CVE_STATUS[CVE-2021-3864] = "not-applicable-config: required config CONFIG_SECURITY_SELINUX is not in linux-aspeed"

CVE_STATUS[CVE-2022-0400] = "not-applicable-config: required config CONFIG_SMC is not in linux-aspeed"

CVE_STATUS[CVE-2022-1247] = "not-applicable-config: required config CONFIG_ROSE is not in linux-aspeed"

CVE_STATUS[CVE-2022-38096] = "not-applicable-config: required config CONFIG_DRM_VMWGFX is not in linux-aspeed"

CVE_STATUS[CVE-2022-4543] = "not-applicable-config: required config CONFIG_PAGE_TABLE_ISOLATION is not in linux-aspeed"

CVE_STATUS[CVE-2023-3397] = "not-applicable-config: required config CONFIG_JFS_FS is not in linux-aspeed"

CVE_STATUS[CVE-2023-3640] = "not-applicable-config: required config CONFIG_X86_64 is not in linux-aspeed"

CVE_STATUS[CVE-2023-39176] = "not-applicable-config: required config CONFIG_SMB_SERVER is not in linux-aspeed"

CVE_STATUS[CVE-2023-39179] = "not-applicable-config: required config CONFIG_SMB_SERVER is not in linux-aspeed"

CVE_STATUS[CVE-2023-39180] = "not-applicable-config: required config CONFIG_SMB_SERVER is not in linux-aspeed"

CVE_STATUS[CVE-2023-4010] = "cpe-stable-backport: the iussue is reported on specific USB usage. Red Hat reports that at least from version 8 it is fixed (Linux kernel 4.18). It seems that the issue is fixed indirectly in newer kernel versions without pointing to any specific commit message."

CVE_STATUS[CVE-2023-52904] = "not-applicable-config: required config CONFIG_SND_USB_AUDIO is not in linux-aspeed"

CVE_STATUS[CVE-2023-6176] = "not-applicable-config: required config CONFIG_TLS is not in linux-aspeed"

CVE_STATUS[CVE-2023-6238] = "not-applicable-config: required config CONFIG_BLK_DEV_INTEGRITY is not in linux-aspeed"

CVE_STATUS[CVE-2023-6240] = "cpe-stable-backport: The vulnerability has been patched in Rocky Linux 8 with kernel version 4.18.0-553.5.1.el8_10 or higher. It seems that the issue is fixed indirectly in newer kernel versions without pointing to any specific commit message."

CVE_STATUS[CVE-2023-6535] = "not-applicable-config: required config CONFIG_NVME_TARGET_TCP is not in linux-aspeed"

# CONFIG_CIFS is enabled for GB200NVL-BMC
# CVE_STATUS[CVE-2023-6610] - applicable

CVE_STATUS[CVE-2023-6679] = "not-applicable-config: required config CONFIG_DPLL is not in linux-aspeed"

CVE_STATUS[CVE-2023-7042] = "not-applicable-config: required config CONFIG_ATH10K is not in linux-aspeed"

CVE_STATUS[CVE-2024-0193] = "not-applicable-config: required config CONFIG_NF_TABLES is not in linux-aspeed"

CVE_STATUS[CVE-2024-52560] = "not-applicable-config: required config CONFIG_NTFS3_FS is not in linux-aspeed"

CVE_STATUS[CVE-2024-57995] = "not-applicable-config: required config CONFIG_ATH12K is not in linux-aspeed"

CVE_STATUS[CVE-2024-58015] = "not-applicable-config: required config CONFIG_ATH12K_DEBUGFS is not in linux-aspeed"

CVE_STATUS[CVE-2024-58097] = "not-applicable-config: required config CONFIG_ATH11K is not in linux-aspeed"

CVE_STATUS[CVE-2025-21751] = "not-applicable-config: mellanox ethernet driver is not in linux-aspeed"

CVE_STATUS[CVE-2025-21833] = "not-applicable-config: required config CONFIG_INTEL_IOMMU is not in linux-aspeed"

CVE_STATUS[CVE-2025-21949] = "not-applicable-platform: Only for loongarch architecture"

CVE_STATUS[CVE-2025-23137] = "not-applicable-config: required config CONFIG_X86_AMD_PSTATE is not in linux-aspeed"

CVE_STATUS[CVE-2025-37803] = "not-applicable-config: required config CONFIG_UDMABUF is not in linux-aspeed"

CVE_STATUS[CVE-2025-37860] = "not-applicable-config: required config CONFIG_SFC is not in linux-aspeed"

CVE_STATUS[CVE-2025-40014] = "not-applicable-config: required config CONFIG_SPI_AMD is not in linux-aspeed"
