#<NetFn>:<Command>:<ChannelMask> // comment
0x00:0x00:0xffff    //<Chassis>:<Get Chassis Capabilities>
0x00:0x01:0xffff    //<Chassis>:<Get Chassis Status>
0x00:0x09:0xffff    //<Chassis>:<Get System Boot Options>
0x04:0x20:0xffff    //<Sensor/Event>:<Get Device SDR Info>
0x04:0x21:0xffff    //<Sensor/Event>:<Get Device SDR>
0x04:0x27:0xffff    //<Sensor/Event>:<Get Sensor Threshold>
0x04:0x29:0xffff    //<Sensor/Event>:<Get Sensor Event Enable>
0x04:0x2B:0xffff    //<Sensor/Event>:<Get Sensor Event Status>
0x04:0x2D:0xffff    //<Sensor/Event>:<Get Sensor Reading>
0x04:0x2F:0xffff    //<Sensor/Event>:<Get Sensor Type>
0x06:0x01:0xffff    //<App>:<Get Device ID>
0x06:0x04:0xffff    //<App>:<Get Self Test Results>
0x06:0x08:0xffff    //<App>:<Get Device GUID>
0x06:0x35:0xffff    //<App>:<Read Event Message Buffer>
0x06:0x37:0xffff    //<App>:<Get System Guid>
0x06:0x41:0xffff    //<App>:<Get Channel Access>
0x06:0x42:0xffff    //<App>:<Get Channel Info>
0x06:0x44:0xffff    //<App>:<Get User Access>
0x06:0x46:0xffff    //<App>:<Get User Name>
0x06:0x4A:0xffff    //<App>:<Get Payload Activation Status>
0x06:0x4B:0xffff    //<App>:<Get Payload Instance Info>
0x06:0x54:0xffff    //<App>:<Get Channel Cipher Suites>
0x0A:0x10:0xffff    //<Storage>:<Get FRU Inventory Area Info>
0x0A:0x11:0xffff    //<Storage>:<Read FRU Data>
0x0A:0x20:0xffff    //<Storage>:<Get SDR Repository Info>
0x0A:0x22:0xffff    //<Storage>:<Reserve SDR Repository>
0x0A:0x23:0xffff    //<Storage>:<Get SDR>
0x0A:0x40:0xffff    //<Storage>:<Get SEL Info>
0x0A:0x42:0xffff    //<Storage>:<Reserve SEL>
0x0A:0x43:0xffff    //<Storage>:<Get SEL Entry>
0x0A:0x44:0xffff    //<Storage>:<Add SEL Entry>
0x0A:0x47:0xffff    //<Storage>:<Clear SEL>
0x0A:0x48:0xffff    //<Storage>:<Get SEL Time>
0x0C:0x02:0xffff    //<Transport>:<Get LAN Configuration Parameters>
0x2C:0x01:0xffff    //<Group Extension>:<Get DCMI Capabilities>
0x2C:0x02:0xffff    //<Group Extension>:<Get Power Reading>
0x2C:0x03:0xffff    //<Group Extension>:<Get Power Limit>
0x2C:0x06:0xffff    //<Group Extension>:<Get Asset Tag>
0x2C:0x07:0xffff    //<Group Extension>:<Get Sensor Info>
0x2C:0x10:0xffff    //<Group Extension>:<Get Temperature Readings>
0x2C:0x3E:0xffff    //<Group Extension>:<Get HPM.x Capabilities>
0x3C:0x30:0xffff    //<Redfish OEM>:<Get Redfish USB Description>
0x3C:0x31:0xffff    //<Redfish OEM>:<Get Redfish USB Virtual Serial Number>
0x3C:0x32:0xffff    //<Redfish OEM>:<Get Redfish Hostname>
0x3C:0x33:0xffff    //<Redfish OEM>:<Get Redfish IPMI Channel Number>
0x3C:0x34:0xffff    //<Redfish OEM>:<Get Redfish UUID>
0x3C:0x35:0xffff    //<Redfish OEM>:<Get Redfish IP Port>
0x3C:0xD1:0xffff    //<OEM>:<Send OEM Status Code>
